
def parseRow(my_list, my_id):

    for row in my_list:
        if row['id'] == my_id:
            return row['name']


def getResourceTypes(my_id):

    resource_types=[{ "id": 1, "name": 'Water', "category": 'Volatile' },
    { "id": 2, "name": 'Hydrogen', "category": 'Volatile' },
    { "id": 3, "name": 'Ammonia', "category": 'Volatile' },
    { "id": 4, "name": 'Nitrogen', "category": 'Volatile' },
    { "id": 5, "name": 'Sulfur Dioxide', "category": 'Volatile' },
    { "id": 6, "name": 'Carbon Dioxide', "category": 'Volatile' },
    { "id": 7, "name": 'Carbon Monoxide', "category": 'Volatile' },
    { "id": 8, "name": 'Methane', "category": 'Volatile' },
    { "id": 9, "name": 'Apatite', "category": 'Organic' },
    { "id": 10, "name": 'Bitumen', "category": 'Organic' },
    { "id": 11, "name": 'Calcite', "category": 'Organic' },
    { "id": 12, "name": 'Feldspar', "category": 'Metal' },
    { "id": 13, "name": 'Olivine', "category": 'Metal' },
    { "id": 14, "name": 'Pyroxene', "category": 'Metal' },
    { "id": 15, "name": 'Coffinite', "category": 'Fissile' },
    { "id": 16, "name": 'Merrillite', "category": 'Rare Earth' },
    { "id": 17, "name": 'Xenotime', "category": 'Rare Earth' },
    { "id": 18, "name": 'Rhabdite', "category": 'Metal' },
    { "id": 19, "name": 'Graphite', "category": 'Metal' },
    { "id": 20, "name": 'Taenite', "category": 'Metal' },
    { "id": 21, "name": 'Troilite', "category": 'Metal' },
    { "id": 22, "name": 'Uraninite', "category": 'Fissile' }]

    return parseRow(resource_types, my_id)


def getSpectralTypes(my_id):

    spectral_types=[{"id": 0, "name": 'C'},
    {"id": 1, "name": 'Cm'},
    {"id": 2, "name": 'Ci'},
    {"id": 3, "name": 'Cs'},
    {"id": 4, "name": 'Cms'},
    {"id": 5, "name": 'Cis'},
    {"id": 6, "name": 'S'},
    {"id": 7, "name": 'Sm'},
    {"id": 8, "name": 'Si'},
    {"id": 9, "name": 'M'},
    {"id": 10, "name": 'I'}]

    return parseRow(spectral_types, my_id)


def getCapableTypes(my_id):

    capable_types=[{"id": 0, "name": 'Empty Lot'},
    {"id": 1, "name": 'Warehouse'},
    {"id": 2, "name": 'Extractor'},
    {"id": 3, "name": 'Refinery'},
    {"id": 4, "name": 'Bioreactor'},
    {"id": 5, "name": 'Factory'},
    {"id": 6, "name": 'Shipyard'},
    {"id": 7, "name": 'Spaceport'},
    {"id": 8, "name": 'Marketplace'},
    {"id": 8, "name": 'Habitat'}]

    return parseRow(capable_types, my_id)


def getClassTypes(my_id):

    class_types=[{"id": 1, "name": 'Pilot'},
    {"id": 2, "name": 'Engineer'},
    {"id": 3, "name": 'Miner'},
    {"id": 4, "name": 'Merchant'},
    {"id": 5, "name": 'Scientist'}]

    return parseRow(class_types, my_id)


def getTitleTypes(my_id):

    title_types=[{"id": 0, "name": 'None'},
    {"id": 1, "name": 'Communications Officer'},
    {"id": 2, "name": 'Teaching Assistant'},
    {"id": 3, "name": 'Librarian'},
    {"id": 4, "name": 'Nurse'},
    {"id": 5, "name": 'Public Safety Officer'},
    {"id": 6, "name": 'Warehouse Worker'},
    {"id": 7, "name": 'Maintenance Technician'},
    {"id": 8, "name": 'Systems Administrator'},
    {"id": 9, "name": 'Structural Engineer'},
    {"id": 10, "name": 'Farmer'},
    {"id": 11, "name": 'Line Cook'},
    {"id": 12, "name": 'Artist'},
    {"id": 13, "name": 'Block Captain'},
    {"id": 14, "name": 'Observatory Technician'},
    {"id": 15, "name": 'Teacher'},
    {"id": 16, "name": 'Historian'},
    {"id": 17, "name": 'Physician Assistant'},
    {"id": 18, "name": 'Security Officer'},
    {"id": 19, "name": 'Logistics Specialist'},
    {"id": 20, "name": 'Electrician'},
    {"id": 21, "name": 'Software Engineer'},
    {"id": 22, "name": 'Life Support Engineer'},
    {"id": 23, "name": 'Field Botanist'},
    {"id": 24, "name": 'Section Cook'},
    {"id": 25, "name": 'Author'},
    {"id": 26, "name": 'Delegate'},
    {"id": 27, "name": 'Cartographer'},
    {"id": 28, "name": 'Professor'},
    {"id": 29, "name": 'Archivist'},
    {"id": 30, "name": 'Resident Physician'},
    {"id": 31, "name": 'Tactical Officer'},
    {"id": 32, "name": 'Warehouse Manager'},
    {"id": 33, "name": 'EVA Technician'},
    {"id": 34, "name": 'Embedded Engineer'},
    {"id": 35, "name": 'Propulsion Engineer'},
    {"id": 36, "name": 'Nutritionist'},
    {"id": 37, "name": 'Kitchen Manager'},
    {"id": 38, "name": 'Musician'},
    {"id": 39, "name": 'Councilor'},
    {"id": 40, "name": 'Navigator'},
    {"id": 41, "name": 'Distinguished Professor'},
    {"id": 42, "name": 'Curator'},
    {"id": 43, "name": 'Physician'},
    {"id": 44, "name": 'Intelligence Officer'},
    {"id": 45, "name": 'Logistics Manager'},
    {"id": 46, "name": 'Facilities Supervisor'},
    {"id": 47, "name": 'Systems Architect'},
    {"id": 48, "name": 'Reactor Engineer'},
    {"id": 49, "name": 'Plant Geneticist'},
    {"id": 50, "name": 'Chef'},
    {"id": 51, "name": 'Actor'},
    {"id": 52, "name": 'Justice'},
    {"id": 53, "name": 'Chief Navigator'},
    {"id": 54, "name": 'Provost'},
    {"id": 55, "name": 'Chief Archivist'},
    {"id": 56, "name": 'Chief Medical Officer'},
    {"id": 57, "name": 'Head of Security'},
    {"id": 58, "name": 'Chief Logistics Officer'},
    {"id": 59, "name": 'Chief Steward'},
    {"id": 60, "name": 'Chief Technology Officer'},
    {"id": 61, "name": 'Head of Engineering'},
    {"id": 62, "name": 'Chief Botanist'},
    {"id": 63, "name": 'Chief Cook'},
    {"id": 64, "name": 'Entertainment Director'},
    {"id": 65, "name": 'High Commander'}]

    return parseRow(title_types, my_id)


def getDepartmentTypes(my_id):

    department_types=[{"id": 1, "name": 'Navigation'},
    {"id": 2, "name": 'Education'},
    {"id": 3, "name": 'Knowledge'},
    {"id": 4, "name": 'Medicine'},
    {"id": 5, "name": 'Security'},
    {"id": 6, "name": 'Logistics'},
    {"id": 7, "name": 'Maintenancet'},
    {"id": 8, "name": 'Technology'},
    {"id": 9, "name": 'Engineering'},
    {"id": 10, "name": 'Food Production'},
    {"id": 11, "name": 'Food Preparation'},
    {"id": 12, "name": 'Arts & Entertainment'},
    {"id": 13, "name": 'Management'}]

    return parseRow(department_types, my_id)


def getCrewCollectionTypes(my_id):

    crew_collection_types=[{"id": 1, "name": 'Arvad Specialist'},
    {"id": 2, "name": 'Arvad Citizen'},
    {"id": 3, "name": 'Arvad Leadership'},
    {"id": 4, "name": 'Adalian'}]

    return parseRow(crew_collection_types, my_id)


def getConstructionStatus(my_id):

    construction_status=[{"id": 0, "name": 'Unplanned'},
    {"id": 1, "name": 'Planned'},
    {"id": 2, "name": 'Under Construction'},
    {"id": 3, "name": 'Operational'}]

    return parseRow(construction_status, my_id)


def getScanStatuses(my_id):

    scan_status=[{"id": 0, "name": 'Unscanned'},
    {"id": 1, "name": 'Surface Scanning'},
    {"id": 2, "name": 'Surface Scanned'},
    {"id": 3, "name": 'Resource Scanning'},
    {"id": 4, "name": 'Resource Scanned'}]

    return parseRow(scan_status, my_id)


def getEntities(my_id):

    entities=[{"id": 1, "name": 'Crew'},
    {"id": 2, "name": 'Crewmate'},
    {"id": 3, "name": 'Asteroid'},
    {"id": 4, "name": 'Lot'},
    {"id": 5, "name": 'Building'},
    {"id": 6, "name": 'Ship'},
    {"id": 7, "name": 'Deposit'},
    {"id": 8, "name": 'Order'},
    {"id": 9, "name": 'Delivery'}]

    return parseRow(entities, my_id)


def getInventories(my_id):

    inventories=[{"id": 1, "name": 'Warehouse Site'},
    {"id": 2, "name": 'Extractor Site'},
    {"id": 3, "name": 'Refinery Site'},
    {"id": 4, "name": 'Bioreactor Site'},
    {"id": 5, "name": 'Factory Site'},
    {"id": 6, "name": 'Shipyard Site'},
    {"id": 7, "name": 'Spaceport Site'},
    {"id": 8, "name": 'Marketplace Site'},
    {"id": 9, "name": 'Habitat Site'},
    {"id": 10, "name": 'Warehouse Primary'},
    {"id": 11, "name": 'Propellant Tiny'},
    {"id": 12, "name": 'Propellant Small'},
    {"id": 13, "name": 'Propellant Medium'},
    {"id": 14, "name": 'Propellant Large'},
    {"id": 15, "name": 'Cargo Small'},
    {"id": 16, "name": 'Cargo Medium'},
    {"id": 17, "name": 'Cargo Large'}]

    return parseRow(inventories, my_id)


def getPermissions(my_id):

    permissions=[{"id": 1, "name": 'Lot Use'},
    {"id": 2, "name": 'Run Process'},
    {"id": 3, "name": 'Add Products'},
    {"id": 4, "name": 'Remove Products'},
    {"id": 5, "name": 'Station Crew'},
    {"id": 6, "name": 'Recruit Crewmate'},
    {"id": 7, "name": 'Dock Ship'},
    {"id": 8, "name": 'Buy'},
    {"id": 9, "name": 'Sell'},
    {"id": 10, "name": 'Limit Buy'},
    {"id": 11, "name": 'Limit Sell'},
    {"id": 12, "name": 'Extract Resources'},
    {"id": 13, "name": 'Assemble Ship'}]

    return parseRow(permissions, my_id)


def getOrders(my_id):

    orders=[{"id": 1, "name": 'Limit Buy'},
    {"id": 2, "name": 'Limit Sell'}]

    return parseRow(orders, my_id)


def getOrderStatus(my_id):

    order_statuses=[{"id": 1, "name": 'Uninitialized'},
    {"id": 2, "name": 'Open'},
    {"id": 3, "name": 'Filled'},
    {"id": 4, "name": 'Cancelled'}]

    return parseRow(getOrderStatus, my_id)


def getCrewTraitTypes(my_id):

    crew_trait_types=[{"id": 1, "name": 'Drive: Survival'},
    {"id": 2, "name": 'Drive: Service'},
    {"id": 3, "name": 'Drive: Glory'},
    {"id": 4, "name": 'Drive: Command'},
    {"id": 5, "name": 'Adventurous'},
    {"id": 6, "name": 'Ambitious'},
    {"id": 7, "name": 'Arrogant'},
    {"id": 8, "name": 'Cautious'},
    {"id": 9, "name": 'Creative'},
    {"id": 10, "name": 'Curious'},
    {"id": 11, "name": 'Fierce'},
    {"id": 12, "name": 'Flexible'},
    {"id": 13, "name": 'Frantic'},
    {"id": 14, "name": 'Hopeful'},
    {"id": 15, "name": 'Independent'},
    {"id": 16, "name": 'Irrational'},
    {"id": 17, "name": 'Loyal'},
    {"id": 18, "name": 'Pragmatic'},
    {"id": 19, "name": 'Rational'},
    {"id": 20, "name": 'Reckless'},
    {"id": 21, "name": 'Regressive'},
    {"id": 22, "name": 'Serious'},
    {"id": 23, "name": 'Steadfast'},
    {"id": 24, "name": 'Council Loyalist'},
    {"id": 25, "name": 'Council Moderate'},
    {"id": 26, "name": 'Independent Moderate'},
    {"id": 27, "name": 'Independent Radical'},
    {"id": 28, "name": 'Navigator'},
    {"id": 29, "name": 'Dietitian'},
    {"id": 30, "name": 'Refiner'},
    {"id": 31, "name": 'Surveyor'},
    {"id": 32, "name": 'Hauler'},
    {"id": 33, "name": 'Optimistic'},
    {"id": 34, "name": 'Thoughtful'},
    {"id": 35, "name": 'Pessimistic'},
    {"id": 36, "name": 'Righteous'},
    {"id": 37, "name": 'Communal'},
    {"id": 38, "name": 'Impartial'},
    {"id": 39, "name": 'Enterprising'},
    {"id": 40, "name": 'Opportunistic'},
    {"id": 41, "name": 'Buster'},
    {"id": 42, "name": 'Mogul'},
    {"id": 43, "name": 'Scholar'},
    {"id": 44, "name": 'Recycler'},
    {"id": 45, "name": 'Mechanic'},
    {"id": 46, "name": 'Operator'},
    {"id": 47, "name": 'Logistician'},
    {"id": 48, "name": 'Experimenter'},
    {"id": 49, "name": 'Builder'},
    {"id": 50, "name": 'Prospector'}]

    return parseRow(crew_trait_types, my_id)


def getProcess(my_id):

    processes=[{"id": 23, "name": "WATER_ELECTROLYSIS"},
    {"id": 24, "name": "WATER_VACUUM_EVAPORATION_DESALINATION"},
    {"id": 25, "name": "SABATIER_PROCESS"},
    {"id": 26, "name": "OLIVINE_ENHANCED_WEATHERING"},
    {"id": 27, "name": "BITUMEN_HYDRO_CRACKING"},
    {"id": 28, "name": "TAENITE_ELECTROLYTIC_REFINING"},
    {"id": 29, "name": "CALCITE_CALCINATION"},
    {"id": 30, "name": "HUELS_PROCESS"},
    {"id": 31, "name": "AMMONIA_CARBONATION"},
    {"id": 32, "name": "SALT_SULFIDIZATION_AND_PHOSPHORIZATION"},
    {"id": 33, "name": "BASIC_FOOD_COOKING_AND_PACKAGING"},
    {"id": 34, "name": "TROILITE_CENTRIFUGAL_FROTH_FLOTATION"},
    {"id": 35, "name": "SILICA_FUSING"},
    {"id": 36, "name": "SILICA_PULTRUSION"},
    {"id": 37, "name": "COPPER_WIRE_DRAWING"},
    {"id": 38, "name": "SALTY_CEMENT_MIXING"},
    {"id": 39, "name": "SALT_SELECTIVE_CRYSTALLIZATION"},
    {"id": 40, "name": "NAPHTHA_STEAM_CRACKING"},
    {"id": 41, "name": "STEEL_ALLOYING"},
    {"id": 42, "name": "SILICA_CARBOTHERMIC_REDUCTION"},
    {"id": 43, "name": "OSTWALD_PROCESS"},
    {"id": 44, "name": "WET_SULFURIC_ACID_PROCESS"},
    {"id": 45, "name": "FUNGAL_SOILBUILDING"},
    {"id": 46, "name": "IRON_OXIDE_AND_SILICA_CARBOTHERMIC_REDUCTION"},
    {"id": 47, "name": "METHANE_STEAM_REFORMING_AND_WATER_GAS_SHIFT"},
    {"id": 48, "name": "ACETYLENE_OXALIC_ACID_PRODUCTION"},
    {"id": 49, "name": "LEAD_SULFIDE_SMELTING"},
    {"id": 50, "name": "TIN_SULFIDE_SMELTING"},
    {"id": 51, "name": "IRON_SULFIDE_ROASTING"},
    {"id": 52, "name": "HABER_BOSCH_PROCESS"},
    {"id": 53, "name": "MOLYBDENUM_DISULFIDE_ROASTING"},
    {"id": 54, "name": "SILICA_GAS_ATOMIZATION"},
    {"id": 55, "name": "SOLDER_MANUFACTURING"},
    {"id": 56, "name": "QUARTZ_FILAMENT_DRAWING_AND_WRAPPING"},
    {"id": 57, "name": "STEEL_BEAM_ROLLING"},
    {"id": 58, "name": "STEEL_SHEET_ROLLING"},
    {"id": 59, "name": "STEEL_PIPE_ROLLING"},
    {"id": 60, "name": "STEEL_WIRE_DRAWING"},
    {"id": 61, "name": "PROPYLENE_AMMOXIDATION"},
    {"id": 62, "name": "PROPYLENE_POLYMERIZATION"},
    {"id": 63, "name": "MAGNESIUM_CHLORIDE_MOLTEN_SALT_ELECTROLYSIS"},
    {"id": 64, "name": "SOLVAY_PROCESS"},
    {"id": 65, "name": "BORON_TRIOXIDE_HYDRATION"},
    {"id": 66, "name": "PYROXENE_ACID_LEACHING_DIGESTION_AND_ION_EXCHANGE"},
    {"id": 67, "name": "APATITE_ACID_EXTRACTION"},
    {"id": 68, "name": "HYDROGEN_COMBUSTION"},
    {"id": 69, "name": "CARBON_MONOXIDE_COMBUSTION"},
    {"id": 70, "name": "BORAX_ACID_EXTRACTION"},
    {"id": 71, "name": "NITROGEN_CRYOCOOLING_AND_FRACTIONAL_DISTILLATION"},
    {"id": 72, "name": "OLIVINE_ACID_LEACHING_AND_CALCINING"},
    {"id": 73, "name": "ANORTHITE_FELDSPAR_ACID_LEACHING_AND_CARBONATION"},
    {"id": 74, "name": "SODIUM_CHLORALKALAI_PROCESS"},
    {"id": 75, "name": "POTASSIUM_CHLORALKALAI_PROCESS"},
    {"id": 76, "name": "APATITE_ACID_RE_EXTRACTION"},
    {"id": 77, "name": "AMMONIUM_CARBONATE_OXALATION"},
    {"id": 78, "name": "XENOTIME_HOT_ACID_LEACHING"},
    {"id": 79, "name": "MERRILLITE_HOT_ACID_LEACHING"},
    {"id": 80, "name": "AMMONIA_CATALYTIC_CRACKING"},
    {"id": 81, "name": "URANINITE_ACID_LEACHING_SOLVENT_EXTRACTION_AND_PRECIPITATION"},
    {"id": 82, "name": "COFFINITE_ACID_LEACHING_SOLVENT_EXTRACTION_AND_PRECIPITATION"},
    {"id": 83, "name": "ALUMINA_FORMING_AND_SINTERING"},
    {"id": 84, "name": "AUSTENITIC_NICHROME_ALLOYING"},
    {"id": 85, "name": "COPPER_WIRE_INSULATING"},
    {"id": 86, "name": "SILICON_CZOCHRALSKI_PROCESS_AND_WAFER_SLICING"},
    {"id": 87, "name": "STEEL_CABLE_LAYING"},
    {"id": 88, "name": "ACRYLONITRILE_POLYMERIZATION"},
    {"id": 89, "name": "SOYBEAN_GROWING"},
    {"id": 90, "name": "BORIC_ACID_THERMAL_DECOMPOSITION"},
    {"id": 91, "name": "LITHIUM_CARBONATE_CHLORINATION"},
    {"id": 92, "name": "LITHIUM_SULFATE_CARBONATION"},
    {"id": 93, "name": "IRON_OXIDE_DIRECT_REDUCTION"},
    {"id": 94, "name": "ZINC_OXIDE_DIRECT_REDUCTION"},
    {"id": 95, "name": "NICKEL_OXIDE_DIRECT_REDUCTION"},
    {"id": 96, "name": "PIDGEON_PROCESS"},
    {"id": 97, "name": "POLYPROPYLENE_CHLORINATION_AND_BASIFICATION"},
    {"id": 98, "name": "POTATO_GROWING"},
    {"id": 99, "name": "RARE_EARTHS_OXALATION_AND_CALCINATION"},
    {"id": 100, "name": "AMMONIA_CHLORINATION"},
    {"id": 101, "name": "HALL_H_ROULT_PROCESS"},
    {"id": 102, "name": "CALCIUM_CHLORIDE_MOLTEN_SALT_ELECTROLYSIS"},
    {"id": 103, "name": "CEMENT_MIXING"},
    {"id": 104, "name": "NATURAL_FLAVORINGS_GROWING"},
    {"id": 105, "name": "YELLOWCAKE_DIGESTION_SOLVENT_EXTRACTION_AND_PRECIPITATION"},
    {"id": 106, "name": "HYDROFLUORIC_ACID_COLD_ELECTROLYSIS"},
    {"id": 107, "name": "RHABDITE_ROASTING_AND_ACID_EXTRACTION"},
    {"id": 108, "name": "FERRITE_SINTERING"},
    {"id": 109, "name": "DIODE_DOPING_AND_ASSEMBLY"},
    {"id": 110, "name": "BALL_VALVE_MACHINING"},
    {"id": 111, "name": "ALUMINIUM_BEAM_ROLLING"},
    {"id": 112, "name": "ALUMINIUM_SHEET_ROLLING"},
    {"id": 113, "name": "ALUMINIUM_PIPE_ROLLING"},
    {"id": 114, "name": "POLYACRYLONITRILE_WEAVING"},
    {"id": 115, "name": "COLD_GAS_THRUSTER_PRINTING"},
    {"id": 116, "name": "POLYACRYLONITRILE_OXIDATION_AND_CARBONIZATION"},
    {"id": 117, "name": "ALUMINIUM_SMALL_PROPELLANT_TANK_ASSEMBLY"},
    {"id": 118, "name": "BOROSILICATE_GLASSMAKING"},
    {"id": 119, "name": "BALL_BEARING_MACHINING_AND_ASSEMBLY"},
    {"id": 120, "name": "LARGE_THRUST_BEARING_MACHINING_AND_ASSEMBLY"},
    {"id": 121, "name": "BORON_TRIOXIDE_MAGNESIOTHERMIC_REDUCTION"},
    {"id": 122, "name": "LITHIUM_CHLORIDE_MOLTEN_SALT_ELECTROLYSIS"},
    {"id": 123, "name": "DIEPOXY_STEP_GROWTH_POLYMERIZATION"},
    {"id": 124, "name": "RARE_EARTH_OXIDES_ION_EXCHANGE"},
    {"id": 125, "name": "CALCIUM_OXIDE_ALUMINOTHERMIC_REDUCTION"},
    {"id": 126, "name": "SODIUM_CHROMATE_ACIDIFICATION_AND_CRYSTALLIZATION"},
    {"id": 127, "name": "SULFURIC_ACID_HOT_CATALYTIC_REDUCTION"},
    {"id": 128, "name": "MOLYBDENUM_TRIOXIDE_ALUMINOTHERMIC_REDUCTION_AND_ALLOYING"},
    {"id": 129, "name": "URANYL_NITRATE_REDOX_AND_PRECIPITATION"},
    {"id": 130, "name": "SODIUM_TUNGSTATE_ION_EXCHANGE_PRECIPITATION_AND_CRYSTALLIZATION"},
    {"id": 131, "name": "STAINLESS_STEEL_ALLOYING"},
    {"id": 132, "name": "BOARD_PRINTING"},
    {"id": 133, "name": "FERRITE_BEAD_INDUCTOR_WINDING"},
    {"id": 134, "name": "CORE_SAMPLER_DRILL_MILLING"},
    {"id": 135, "name": "CORE_SAMPLER_THRUSTER_ASSEMBLY"},
    {"id": 136, "name": "PARABOLIC_DISH_ASSEMBLY"},
    {"id": 137, "name": "PHOTOVOLTAIC_PANEL_AMORPHIZATION_AND_ASSEMBLY"},
    {"id": 138, "name": "LIPO_BATTERY_ASSEMBLY"},
    {"id": 139, "name": "NEODYMIUM_OXIDE_CHLORINATION"},
    {"id": 141, "name": "SODIUM_DICHROMATE_HOT_SULFUR_REDUCTION"},
    {"id": 142, "name": "PHOTORESIST_EPOXY_STOICHIOMETRY_AND_PACKAGING"},
    {"id": 143, "name": "AMMONIUM_DIURANATE_CALCINATION_AND_HYDROGEN_REDUCTION"},
    {"id": 144, "name": "AMMONIUM_PARATUNGSTATE_CALCINATION_AND_HYDROGEN_REDUCTION"},
    {"id": 145, "name": "ENGINE_BELL_ADDITIVE_MANUFACTURING"},
    {"id": 146, "name": "STEEL_TRUSS_CONSTRUCTION"},
    {"id": 147, "name": "ALUMINIUM_HULL_PLATE_CONSTRUCTION"},
    {"id": 148, "name": "ALUMINIUM_TRUSS_CONSTRUCTION"},
    {"id": 149, "name": "CARGO_MODULE_CONSTRUCTION"},
    {"id": 150, "name": "ALUMINIUM_PRESSURE_VESSEL_CONSTRUCTION"},
    {"id": 151, "name": "ALUMINIUM_PROPELLANT_TANK_CONSTRUCTION"},
    {"id": 152, "name": "SHUTTLE_HULL_CONSTRUCTION"},
    {"id": 153, "name": "LIGHT_TRANSPORT_HULL_CONSTRUCTION"},
    {"id": 154, "name": "CARGO_RING_CONSTRUCTION"},
    {"id": 155, "name": "HEAVY_TRANSPORT_HULL_CONSTRUCTION"},
    {"id": 156, "name": "TUNGSTEN_GAS_ATOMIZATION"},
    {"id": 157, "name": "HYDROGEN_CRYOCOOLING_AND_REACTOR_CONSUMABLES_STOICHIOMETRY"},
    {"id": 158, "name": "STAINLESS_STEEL_SHEET_ROLLING"},
    {"id": 159, "name": "STAINLESS_STEEL_PIPE_ROLLING"},
    {"id": 160, "name": "SILICON_WAFER_CPU_PHOTOLITHOGRAPHY_BALL_BONDING_AND_ENCAPSULATION"},
    {"id": 161, "name": "CORE_SAMPLER_ASSEMBLY"},
    {"id": 162, "name": "NEODYMIUM_TRICHLORIDE_VACUUM_CALCIOTHERMIC_REDUCTION"},
    {"id": 163, "name": "NEODYMIUM_TRICHLORIDE_MOLTEN_SALT_ELECTROLYSIS"},
    {"id": 165, "name": "CHROMIA_ALUMINOTHERMIC_REDUCTION"},
    {"id": 166, "name": "URANIUM_DIOXIDE_OXIDATION"},
    {"id": 167, "name": "LEACHED_COFFINITE_FROTH_FLOTATION_SOLVENT_EXTRACTION_AND_PRECIPITATION"},
    {"id": 168, "name": "ND_YAG_CZOCHRALSKI_PROCESS"},
    {"id": 169, "name": "NICHROME_ALLOYING"},
    {"id": 170, "name": "MAGNET_SINTERING"},
    {"id": 171, "name": "URANIUM_TETRAFLUORIDE_FLUORIDATION"},
    {"id": 172, "name": "URANIUM_HEXAFLUORIDE_CENTRIFUGE_CASCADE_ENRICHMENT"},
    {"id": 173, "name": "ND_YAG_LASER_ASSEMBLY"},
    {"id": 174, "name": "THIN_FILM_RESISTOR_SPUTTERING_AND_LASER_TRIMMING"},
    {"id": 175, "name": "HEUF_MAGNESIOTHERMIC_REDUCTION_AND_FINE_DIVISION"},
    {"id": 176, "name": "SPIRULINA_AND_CHLORELLA_ALGAE_GROWING"},
    {"id": 177, "name": "PEDOT_BACTERIA_CULTURING"},
    {"id": 178, "name": "BPA_BACTERIA_CULTURING"},
    {"id": 179, "name": "POTASSIUM_HYDROXIDE_CARBONATION"},
    {"id": 180, "name": "NOVOLAK_BACTERIA_CULTURING"},
    {"id": 181, "name": "FERROCHROMIUM_ALLOYING"},
    {"id": 182, "name": "POTASSIUM_CARBONATE_FLUORIDATION"},
    {"id": 183, "name": "RHABDITE_SLAG_ACID_LEACHING"},
    {"id": 184, "name": "TANTALATE_NIOBATE_LIQUID_LIQUID_EXTRACTION_AND_REDOX"},
    {"id": 185, "name": "CARBON_DIOXIDE_ARC_DECOMPOSITION"},
    {"id": 186, "name": "POTASSIUM_HEPTAFLUOROTANTALATE_SODIOTHERMIC_REDUCTION"},
    {"id": 187, "name": "RHABDITE_CARBOTHERMIC_REDUCTION"},
    {"id": 188, "name": "POLYMER_TANTALUM_CAPACITOR_ASSEMBLY"},
    {"id": 189, "name": "SURFACE_MOUNT_DEVICE_REEL_ASSEMBLY"},
    {"id": 190, "name": "PICK_AND_PLACE_BOARD_POPULATION"},
    {"id": 191, "name": "MOTOR_STATOR_ASSEMBLY"},
    {"id": 192, "name": "MOTOR_ROTOR_ASSEMBLY"},
    {"id": 193, "name": "BRUSHLESS_MOTOR_ASSEMBLY"},
    {"id": 194, "name": "LANDING_LEG_ASSEMBLY"},
    {"id": 195, "name": "LANDING_AUGER_ASSEMBLY"},
    {"id": 196, "name": "PUMP_ASSEMBLY"},
    {"id": 197, "name": "ANTENNA_ASSEMBLY"},
    {"id": 198, "name": "FIBER_OPTIC_GYROSCOPE_ASSEMBLY"},
    {"id": 199, "name": "STAR_TRACKER_ASSEMBLY"},
    {"id": 200, "name": "COMPUTER_ASSEMBLY"},
    {"id": 201, "name": "CONTROL_MOMENT_GYROSCOPE_ASSEMBLY"},
    {"id": 202, "name": "ROBOTIC_ARM_ASSEMBLY"},
    {"id": 203, "name": "FELDSPAR_ALUMINIUM_HYDROXIDE_CALCINATION"},
    {"id": 204, "name": "FERROCHROMIUM_ROASTING_AND_HOT_BASE_LEACHING"},
    {"id": 205, "name": "BERYLLIUM_CARBONATE_CALCINATION"},
    {"id": 206, "name": "BERYLLIA_FORMING_AND_SINTERING"},
    {"id": 207, "name": "SILICON_WAFER_CCD_PHOTOLITHOGRAPHY_BALL_BONDING_AND_PACKAGING"},
    {"id": 208, "name": "HEAT_EXCHANGER_ASSEMBLY"},
    {"id": 209, "name": "TURBOPUMP_ASSEMBLY"},
    {"id": 210, "name": "LASER_DIODE_DOPING_AMORPHIZATION_AND_ASSEMBLY"},
    {"id": 211, "name": "SEPARATOR_CENTRIFUGE_ASSEMBLY"},
    {"id": 212, "name": "FUEL_MAKE_UP_TANK_ASSEMBLY"},
    {"id": 213, "name": "NEON_MAKE_UP_TANK_ASSEMBLY"},
    {"id": 214, "name": "LIGHTBULB_END_MODERATORS_ASSEMBLY"},
    {"id": 215, "name": "COLD_GAS_TORQUE_THRUSTER_PRINTING"},
    {"id": 216, "name": "FUSED_QUARTZ_LIGHTBULB_ADDITIVE_SUBTRACTIVE_ASSEMBLY"},
    {"id": 217, "name": "REACTOR_PLUMBING_ASSEMBLY_"},
    {"id": 218, "name": "FLOW_DIVIDER_MODERATOR_ASSEMBLY"},
    {"id": 219, "name": "NUCLEAR_LIGHTBULB_ASSEMBLY"},
    {"id": 220, "name": "REACTOR_SHELL_ASSEMBLY"},
    {"id": 221, "name": "CLOSED_CYCLE_GAS_CORE_NUCLEAR_REACTOR_ENGINE_ASSEMBLY"},
    {"id": 222, "name": "HABITATION_MODULE_ASSEMBLY"},
    {"id": 223, "name": "MOBILITY_MODULE_ASSEMBLY"},
    {"id": 224, "name": "FLUIDS_AUTOMATION_MODULE_ASSEMBLY"},
    {"id": 225, "name": "SOLIDS_AUTOMATION_MODULE_ASSEMBLY"},
    {"id": 226, "name": "TERRAIN_INTERFACE_MODULE_ASSEMBLY"},
    {"id": 227, "name": "AVIONICS_MODULE_ASSEMBLY"},
    {"id": 228, "name": "ESCAPE_MODULE_ASSEMBLY"},
    {"id": 229, "name": "ATTITUDE_CONTROL_MODULE_ASSEMBLY"},
    {"id": 230, "name": "POWER_MODULE_ASSEMBLY"},
    {"id": 231, "name": "THERMAL_MODULE_ASSEMBLY"},
    {"id": 232, "name": "PROPULSION_MODULE_ASSEMBLY"},
    {"id": 233, "name": "SULFUR_DIOXIDE_PLASMA_CATALYSIS"},
    {"id": 234, "name": "PARKES_PROCESS"},
    {"id": 235, "name": "BICARBONATE_SOLVAY_PROCESS"},
    {"id": 236, "name": "SOLVAY_HOU_PROCESS"},
    {"id": 237, "name": "BICARBONATE_SOLVAY_HOU_PROCESS"},
    {"id": 238, "name": "SODIUM_BICARBONATE_CALCINATION"},
    {"id": 239, "name": "EPOXY_STOICHIOMETRY_AND_PACKAGING"},
    {"id": 240, "name": "PEDOT_ALGAE_GROWING"},
    {"id": 241, "name": "BPA_ALGAE_GROWING"},
    {"id": 242, "name": "NOVOLAK_ALGAE_GROWING"}]

    return parseRow(crew_trait_types, my_id)


def getProducts(my_id):

    products=[{"id": 1, "name": "WATER"},
    {"id": 1, "name": "WATER"},
    {"id": 2, "name": "HYDROGEN"},
    {"id": 3, "name": "AMMONIA"},
    {"id": 4, "name": "NITROGEN"},
    {"id": 5, "name": "SULFUR_DIOXIDE"},
    {"id": 6, "name": "CARBON_DIOXIDE"},
    {"id": 7, "name": "CARBON_MONOXIDE"},
    {"id": 8, "name": "METHANE"},
    {"id": 9, "name": "APATITE"},
    {"id": 10, "name": "BITUMEN"},
    {"id": 11, "name": "CALCITE"},
    {"id": 12, "name": "FELDSPAR"},
    {"id": 13, "name": "OLIVINE"},
    {"id": 14, "name": "PYROXENE"},
    {"id": 15, "name": "COFFINITE"},
    {"id": 16, "name": "MERRILLITE"},
    {"id": 17, "name": "XENOTIME"},
    {"id": 18, "name": "RHABDITE"},
    {"id": 19, "name": "GRAPHITE"},
    {"id": 20, "name": "TAENITE"},
    {"id": 21, "name": "TROILITE"},
    {"id": 22, "name": "URANINITE"},
    {"id": 23, "name": "OXYGEN"},
    {"id": 24, "name": "DEIONIZED_WATER"},
    {"id": 25, "name": "SALTS"},
    {"id": 26, "name": "SILICA"},
    {"id": 27, "name": "NAPHTHA"},
    {"id": 28, "name": "SODIUM_BICARBONATE"},
    {"id": 29, "name": "IRON"},
    {"id": 30, "name": "COPPER"},
    {"id": 31, "name": "NICKEL"},
    {"id": 32, "name": "QUICKLIME"},
    {"id": 33, "name": "ACETYLENE"},
    {"id": 34, "name": "AMMONIUM_CARBONATE"},
    {"id": 35, "name": "TRIPLE_SUPERPHOSPHATE"},
    {"id": 36, "name": "PHOSPHATE_AND_SULFATE_SALTS"},
    {"id": 37, "name": "IRON_SULFIDE"},
    {"id": 38, "name": "LEAD_SULFIDE"},
    {"id": 39, "name": "TIN_SULFIDE"},
    {"id": 40, "name": "MOLYBDENUM_DISULFIDE"},
    {"id": 41, "name": "FUSED_QUARTZ"},
    {"id": 42, "name": "FIBERGLASS"},
    {"id": 43, "name": "BARE_COPPER_WIRE"},
    {"id": 44, "name": "CEMENT"},
    {"id": 45, "name": "SODIUM_CHLORIDE"},
    {"id": 46, "name": "POTASSIUM_CHLORIDE"},
    {"id": 47, "name": "BORAX"},
    {"id": 48, "name": "LITHIUM_CARBONATE"},
    {"id": 49, "name": "MAGNESIUM_CHLORIDE"},
    {"id": 50, "name": "PROPYLENE"},
    {"id": 51, "name": "SULFUR"},
    {"id": 52, "name": "STEEL"},
    {"id": 53, "name": "SILICON"},
    {"id": 54, "name": "NITRIC_ACID"},
    {"id": 55, "name": "SULFURIC_ACID"},
    {"id": 56, "name": "SOIL"},
    {"id": 57, "name": "FERROSILICON"},
    {"id": 58, "name": "WEATHERED_OLIVINE"},
    {"id": 59, "name": "OXALIC_ACID"},
    {"id": 60, "name": "SILVER"},
    {"id": 61, "name": "GOLD"},
    {"id": 62, "name": "TIN"},
    {"id": 63, "name": "IRON_OXIDE"},
    {"id": 64, "name": "SPIRULINA_AND_CHLORELLA_ALGAE"},
    {"id": 65, "name": "MOLYBDENUM_TRIOXIDE"},
    {"id": 66, "name": "SILICA_POWDER"},
    {"id": 67, "name": "SOLDER"},
    {"id": 68, "name": "FIBER_OPTIC_CABLE"},
    {"id": 69, "name": "STEEL_BEAM"},
    {"id": 70, "name": "STEEL_SHEET"},
    {"id": 71, "name": "STEEL_PIPE"},
    {"id": 72, "name": "STEEL_WIRE"},
    {"id": 73, "name": "ACRYLONITRILE"},
    {"id": 74, "name": "POLYPROPYLENE"},
    {"id": 75, "name": "MAGNESIUM"},
    {"id": 76, "name": "CHLORINE"},
    {"id": 77, "name": "SODIUM_CARBONATE"},
    {"id": 78, "name": "CALCIUM_CHLORIDE"},
    {"id": 79, "name": "BORIA"},
    {"id": 80, "name": "LITHIUM_SULFATE"},
    {"id": 81, "name": "HYDROCHLORIC_ACID"},
    {"id": 82, "name": "HYDROFLUORIC_ACID"},
    {"id": 83, "name": "PHOSPHORIC_ACID"},
    {"id": 84, "name": "BORIC_ACID"},
    {"id": 85, "name": "ZINC_OXIDE"},
    {"id": 86, "name": "NICKEL_OXIDE"},
    {"id": 87, "name": "MAGNESIA"},
    {"id": 88, "name": "ALUMINA"},
    {"id": 89, "name": "SODIUM_HYDROXIDE"},
    {"id": 90, "name": "POTASSIUM_HYDROXIDE"},
    {"id": 91, "name": "SOYBEANS"},
    {"id": 92, "name": "POTATOES"},
    {"id": 93, "name": "AMMONIUM_OXALATE"},
    {"id": 94, "name": "RARE_EARTH_SULFATES"},
    {"id": 95, "name": "FERROCHROMIUM"},
    {"id": 96, "name": "YELLOWCAKE"},
    {"id": 97, "name": "ALUMINA_CERAMIC"},
    {"id": 98, "name": "AUSTENITIC_NICHROME"},
    {"id": 99, "name": "COPPER_WIRE"},
    {"id": 100, "name": "SILICON_WAFER"},
    {"id": 101, "name": "STEEL_CABLE"},
    {"id": 102, "name": "POLYACRYLONITRILE"},
    {"id": 103, "name": "NATURAL_FLAVORINGS"},
    {"id": 104, "name": "PLATINUM"},
    {"id": 105, "name": "LITHIUM_CHLORIDE"},
    {"id": 106, "name": "ZINC"},
    {"id": 107, "name": "EPICHLOROHYDRIN"},
    {"id": 108, "name": "BISPHENOL_A"},
    {"id": 109, "name": "RARE_EARTH_OXIDES"},
    {"id": 110, "name": "AMMONIUM_CHLORIDE"},
    {"id": 111, "name": "ALUMINIUM"},
    {"id": 112, "name": "CALCIUM"},
    {"id": 113, "name": "SODIUM_CHROMATE"},
    {"id": 114, "name": "LEACHED_COFFINITE"},
    {"id": 115, "name": "URANYL_NITRATE"},
    {"id": 116, "name": "FLUORINE"},
    {"id": 117, "name": "SODIUM_TUNGSTATE"},
    {"id": 118, "name": "FERRITE"},
    {"id": 119, "name": "DIODE"},
    {"id": 120, "name": "LASER_DIODE"},
    {"id": 121, "name": "BALL_VALVE"},
    {"id": 122, "name": "ALUMINIUM_BEAM"},
    {"id": 123, "name": "ALUMINIUM_SHEET"},
    {"id": 124, "name": "ALUMINIUM_PIPE"},
    {"id": 125, "name": "POLYACRYLONITRILE_FABRIC"},
    {"id": 126, "name": "COLD_GAS_THRUSTER"},
    {"id": 127, "name": "COLD_GAS_TORQUE_THRUSTER"},
    {"id": 128, "name": "CARBON_FIBER"},
    {"id": 129, "name": "FOOD"},
    {"id": 130, "name": "SMALL_PROPELLANT_TANK"},
    {"id": 131, "name": "BOROSILICATE_GLASS"},
    {"id": 132, "name": "BALL_BEARING"},
    {"id": 133, "name": "LARGE_THRUST_BEARING"},
    {"id": 134, "name": "BORON"},
    {"id": 135, "name": "LITHIUM"},
    {"id": 136, "name": "EPOXY"},
    {"id": 137, "name": "NEODYMIUM_OXIDE"},
    {"id": 138, "name": "YTTRIA"},
    {"id": 139, "name": "SODIUM_DICHROMATE"},
    {"id": 140, "name": "NOVOLAK_PREPOLYMER_RESIN"},
    {"id": 141, "name": "FERROMOLYBDENUM"},
    {"id": 142, "name": "AMMONIUM_DIURANATE"},
    {"id": 143, "name": "AMMONIUM_PARATUNGSTATE"},
    {"id": 144, "name": "ENGINE_BELL"},
    {"id": 145, "name": "STEEL_TRUSS"},
    {"id": 146, "name": "ALUMINIUM_HULL_PLATE"},
    {"id": 147, "name": "ALUMINIUM_TRUSS"},
    {"id": 148, "name": "CARGO_MODULE"},
    {"id": 149, "name": "PRESSURE_VESSEL"},
    {"id": 150, "name": "PROPELLANT_TANK"},
    {"id": 151, "name": "STAINLESS_STEEL"},
    {"id": 152, "name": "BARE_CIRCUIT_BOARD"},
    {"id": 153, "name": "FERRITE_BEAD_INDUCTOR"},
    {"id": 154, "name": "CORE_DRILL_SAMPLER"},
    {"id": 155, "name": "CORE_DRILL_THRUSTER"},
    {"id": 156, "name": "PARABOLIC_DISH"},
    {"id": 157, "name": "PHOTOVOLTAIC_PANEL"},
    {"id": 158, "name": "LIPO_BATTERY"},
    {"id": 159, "name": "NEODYMIUM_TRICHLORIDE"},
    {"id": 161, "name": "CHROMIA"},
    {"id": 162, "name": "PHOTORESIST_EPOXY"},
    {"id": 163, "name": "URANIUM_DIOXIDE"},
    {"id": 164, "name": "TUNGSTEN"},
    {"id": 165, "name": "SHUTTLE_HULL"},
    {"id": 166, "name": "LIGHT_TRANSPORT_HULL"},
    {"id": 167, "name": "CARGO_RING"},
    {"id": 168, "name": "HEAVY_TRANSPORT_HULL"},
    {"id": 169, "name": "TUNGSTEN_POWDER"},
    {"id": 170, "name": "HYDROGEN_PROPELLANT"},
    {"id": 171, "name": "STAINLESS_STEEL_SHEET"},
    {"id": 172, "name": "STAINLESS_STEEL_PIPE"},
    {"id": 173, "name": "CCD"},
    {"id": 174, "name": "COMPUTER_CHIP"},
    {"id": 175, "name": "CORE_DRILL"},
    {"id": 176, "name": "NEODYMIUM"},
    {"id": 178, "name": "CHROMIUM"},
    {"id": 179, "name": "URANIUM_TETRAFLUORIDE"},
    {"id": 180, "name": "PURE_NITROGEN"},
    {"id": 181, "name": "ND_YAG_LASER_ROD"},
    {"id": 182, "name": "NICHROME"},
    {"id": 183, "name": "NEODYMIUM_MAGNET"},
    {"id": 184, "name": "UNENRICHED_URANIUM_HEXAFLUORIDE"},
    {"id": 185, "name": "HIGHLY_ENRICHED_URANIUM_HEXAFLUORIDE"},
    {"id": 186, "name": "ND_YAG_LASER"},
    {"id": 187, "name": "THIN_FILM_RESISTOR"},
    {"id": 188, "name": "HIGHLY_ENRICHED_URANIUM_POWDER"},
    {"id": 189, "name": "LEACHED_FELDSPAR"},
    {"id": 190, "name": "ROASTED_RHABDITE"},
    {"id": 191, "name": "RHABDITE_SLAG"},
    {"id": 192, "name": "POTASSIUM_CARBONATE"},
    {"id": 193, "name": "HYDROGEN_HEPTAFLUOROTANTALATE_AND_NIOBATE"},
    {"id": 194, "name": "LEAD"},
    {"id": 195, "name": "POTASSIUM_FLUORIDE"},
    {"id": 196, "name": "POTASSIUM_HEPTAFLUOROTANTALATE"},
    {"id": 197, "name": "DIEPOXY_PREPOLYMER_RESIN"},
    {"id": 199, "name": "TANTALUM"},
    {"id": 200, "name": "PEDOT"},
    {"id": 201, "name": "POLYMER_TANTALUM_CAPACITOR"},
    {"id": 202, "name": "SURFACE_MOUNT_DEVICE_REEL"},
    {"id": 203, "name": "CIRCUIT_BOARD"},
    {"id": 204, "name": "BRUSHLESS_MOTOR_STATOR"},
    {"id": 205, "name": "BRUSHLESS_MOTOR_ROTOR"},
    {"id": 206, "name": "BRUSHLESS_MOTOR"},
    {"id": 207, "name": "LANDING_LEG"},
    {"id": 208, "name": "LANDING_AUGER"},
    {"id": 209, "name": "PUMP"},
    {"id": 210, "name": "RADIO_ANTENNA"},
    {"id": 211, "name": "FIBER_OPTIC_GYROSCOPE"},
    {"id": 212, "name": "STAR_TRACKER"},
    {"id": 213, "name": "COMPUTER"},
    {"id": 214, "name": "CONTROL_MOMENT_GYROSCOPE"},
    {"id": 215, "name": "ROBOTIC_ARM"},
    {"id": 217, "name": "BERYLLIUM_CARBONATE"},
    {"id": 218, "name": "BERYLLIA"},
    {"id": 219, "name": "BERYLLIA_CERAMIC"},
    {"id": 220, "name": "NEON"},
    {"id": 221, "name": "HEAT_EXCHANGER"},
    {"id": 222, "name": "TURBOPUMP"},
    {"id": 224, "name": "NEON_FUEL_SEPARATOR_CENTRIFUGE"},
    {"id": 225, "name": "FUEL_MAKE_UP_TANK"},
    {"id": 226, "name": "NEON_MAKE_UP_TANK"},
    {"id": 227, "name": "LIGHTBULB_END_MODERATORS"},
    {"id": 229, "name": "FUSED_QUARTZ_LIGHTBULB_TUBE"},
    {"id": 230, "name": "REACTOR_PLUMBING_ASSEMBLY"},
    {"id": 231, "name": "FLOW_DIVIDER_MODERATOR"},
    {"id": 232, "name": "NUCLEAR_LIGHTBULB"},
    {"id": 233, "name": "COMPOSITE_OVERWRAPPED_REACTOR_SHELL"},
    {"id": 234, "name": "CLOSED_CYCLE_GAS_CORE_NUCLEAR_REACTOR_ENGINE"},
    {"id": 235, "name": "HABITATION_MODULE"},
    {"id": 236, "name": "MOBILITY_MODULE"},
    {"id": 237, "name": "FLUIDS_AUTOMATION_MODULE"},
    {"id": 238, "name": "SOLIDS_AUTOMATION_MODULE"},
    {"id": 239, "name": "TERRAIN_INTERFACE_MODULE"},
    {"id": 240, "name": "AVIONICS_MODULE"},
    {"id": 241, "name": "ESCAPE_MODULE"},
    {"id": 242, "name": "ATTITUDE_CONTROL_MODULE"},
    {"id": 243, "name": "POWER_MODULE"},
    {"id": 244, "name": "THERMAL_MODULE"},
    {"id": 245, "name": "PROPULSION_MODULE"}]

    return parseRow(products, my_id)


