version: '3'

services:
  mainnet:
    image: eqlabs/pathfinder:latest
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    env_file:
      - pathfinder-mainnet-var.env
    volumes:
     - mainnet:/usr/share/pathfinder/data
    ports:
      - 9545:9545

  apibara:
    image: quay.io/apibara/starknet:8a5ff0593bc9eb561ade52535eaef489570eef08
    ports:
    - 6171:7171
    depends_on:
    - mainnet
    restart: always
    command:
      - start
      - --data
      - "/data/dna"
      - --rpc
      - "http://mainnet:9545/rpc/v0.2"
    environment:
    - OTEL_SDK_DISABLED=true
    volumes:
      - apibara-data:/data/dna
    links:
    - mainnet

volumes:
  mainnet:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/bios/apibara_dna/mainnet/pathfinder_data
  apibara-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/bios/apibara_dna/mainnet/dna_data
